export type SoulGallerySource = "imagic6" | "imya";

export type SoulGalleryItem = {
  id: string;
  title: string;
  englishTitle: string;
  source: SoulGallerySource;
  category: string;
  image: string;
  width: number;
  height: number;
  description: string;
  prompt: string;
};

export const soulGalleryCatalog: SoulGalleryItem[] = [
  {
    id: "neon-rain-night",
    title: "霓虹雨夜",
    englishTitle: "Neon Rain Night",
    source: "imagic6",
    category: "未来幻想",
    image: "/soul-gallery/imagic6/neon-rain-night.webp",
    width: 1280,
    height: 960,
    description: "雨雾、霓虹与湿润街面的赛博城市电影镜头。",
    prompt: "赛博朋克城市夜景，湿润街道反光，霓虹蓝粉灯牌，低角度广角镜头，电影级构图，雨雾氛围，超细节，8k",
  },
  {
    id: "starport-voyage",
    title: "星港远航",
    englishTitle: "Starport Voyage",
    source: "imagic6",
    category: "未来幻想",
    image: "/soul-gallery/imagic6/starport-voyage.webp",
    width: 1280,
    height: 853,
    description: "异星地表与巨大行星环构成的史诗远航。",
    prompt: "宇航员站在异星地表，远处巨大行星与环带，沙尘与冷光交织，史诗感，超现实风景，精细材质",
  },
  {
    id: "future-auto-poster",
    title: "未来车展海报",
    englishTitle: "Future Auto Show Poster",
    source: "imagic6",
    category: "商业视觉",
    image: "/soul-gallery/imagic6/future-auto-poster.webp",
    width: 1280,
    height: 853,
    description: "低趴超跑、金属高光与夜色赛道的产品海报。",
    prompt: "未来超跑，低趴车身，霓虹灯条，运动模糊，金属高光，夜色赛道，科技质感，海报级产品展示",
  },
  {
    id: "silver-hair-moon",
    title: "冷月银发",
    englishTitle: "Silver Hair Under Cold Moon",
    source: "imagic6",
    category: "东方美学",
    image: "/soul-gallery/imagic6/silver-hair-moon.webp",
    width: 1280,
    height: 960,
    description: "冷月色轮廓光下的银发幻想人物插画。",
    prompt: "银发少女，精致五官，柔和轮廓光，梦幻背景，浅景深，华丽服饰，明亮眼眸，高级插画质感",
  },
  {
    id: "cloud-metropolis",
    title: "云端主城",
    englishTitle: "Cloud Metropolis",
    source: "imagic6",
    category: "未来幻想",
    image: "/soul-gallery/imagic6/cloud-metropolis.webp",
    width: 1280,
    height: 960,
    description: "轻雾与金蓝光线包围的天空奇幻建筑。",
    prompt: "云端城堡，漂浮在天空之上，柔和光影，轻雾环绕，奇幻建筑细节，金蓝色调，史诗氛围",
  },
  {
    id: "future-dome-showroom",
    title: "未来穹顶展厅",
    englishTitle: "Future Dome Showroom",
    source: "imagic6",
    category: "空间设计",
    image: "/soul-gallery/imagic6/future-dome-showroom.webp",
    width: 1280,
    height: 960,
    description: "半透明穹顶、蓝紫灯带与柔雾构成的未来展厅。",
    prompt: "未来建筑空间，半透明穹顶，柔雾环境，蓝紫灯带，极简结构，超现代空间摄影",
  },
  {
    id: "glass-console",
    title: "玻璃拟态控制台",
    englishTitle: "Glassmorphism Console",
    source: "imagic6",
    category: "空间设计",
    image: "/soul-gallery/imagic6/glass-console.webp",
    width: 1280,
    height: 853,
    description: "层级清晰的蓝紫玻璃拟态科技控制台。",
    prompt: "未来 UI 设计界面，玻璃拟态面板，蓝紫渐变，清晰层级，科技信息卡，现代 SaaS 风格",
  },
  {
    id: "deepsea-whale",
    title: "深海巨鲸",
    englishTitle: "Abyssal Whale",
    source: "imagic6",
    category: "未来幻想",
    image: "/soul-gallery/imagic6/deepsea-whale.webp",
    width: 1025,
    height: 1535,
    description: "幽蓝深海里，巨鲸穿过微光与漂浮粒子。",
    prompt: "深海巨鲸缓慢游过幽蓝海沟，微弱天光穿透海面形成体积光，周围漂浮细小发光水母与粒子，潜水员作为尺度参照，神秘宁静，电影级构图，超现实海洋幻想，细节丰富，4:5",
  },
  {
    id: "ultra-luxury-perfume-portrait",
    title: "Ultra Luxury Perfume Portrait",
    englishTitle: "奢华香水人像",
    source: "imya",
    category: "商业视觉",
    image: "/soul-gallery/imya/ultra-luxury-perfume-portrait.webp",
    width: 848,
    height: 1200,
    description: "深红丝绸与晶透香氛组成的奢华品牌广告。",
    prompt: "Ultra-luxury Dior perfume advertisement, cinematic studio lighting, deep red monochrome aesthetic. A beautiful elegant East Asian woman with smooth glowing skin and soft makeup, loose wavy brown hair, wearing a red silky satin shirt with soft folds and glossy highlights. She is holding a Dior perfume bottle (same shape as reference) close to her face with a delicate grip. Bottle is crystal clear with soft pink liquid, reflective glass, metallic cap, luxury finish, subtle glow and light reflections. Composition: Close-up portrait, chest-up framing. Model slightly tilted head, soft confident expression. Sharp focus on face + perfume bottle. Background: rich deep red silk fabric waves, soft gradients, luxury feel. Lighting: Warm cinematic key light from front, Soft rim light from side for glow, Subtle specular highlights on skin and satin shirt, High-end beauty retouch look. Foreground elements: Dark marble table surface, Red roses, petals scattered, Glass candle with warm flame, Dior ribbon placed casually. Text layout (minimal luxury style): Top left: 'DIOR' (elegant serif font). Below icons (thin gold line icons): Timeless Elegance, Exquisite Scent, Long Lasting Fragrance, Iconic Design. Color palette: Deep red, burgundy, gold accents, warm skin tones. Style keywords: ultra realistic, 8k, fashion photography, luxury branding, Dior campaign, glossy finish, cinematic, high contrast, premium aesthetic, shallow depth of field",
  },
  {
    id: "oriental-dreamy-beauty-illustration",
    title: "Oriental Dreamy Beauty Illustration",
    englishTitle: "东方梦境美人插画",
    source: "imya",
    category: "东方美学",
    image: "/soul-gallery/imya/oriental-dreamy-beauty-illustration.webp",
    width: 675,
    height: 1199,
    description: "镜面、碎片与红色礼服交织的东方叙事。",
    prompt: "一位东方幻想成年美女正缓缓走向一面高大的镜子，画面为 9:16 竖版构图，摄像机位于她的左后方，以略带电影感的中远景视角捕捉她的身影。她是画面的绝对视觉中心，背影优雅迷人，身穿一袭华贵的红色礼服，礼服具有高级定制感，面料精致，细节丰富，带有层叠刺绣、珠饰或立体纹理。礼服为露肩设计，并带有深 V 领口，整体华丽、性感但高级克制，充分展现肩颈线条、锁骨气质与身体曲线。\n\n她正朝镜子走去，身体以背面和左后侧为主，姿态优雅从容。镜子中清晰映出她的正面形象，镜中她的面容精致美丽，神情安静而富有故事感，同时可以看到她优美的锁骨，以及饱满胸部上半部分自然柔和的轮廓，整体呈现高级、唯美、迷人的女性气质。\n\n在镜子四周以及画面周围，漂浮着大量破碎镜片，这些镜片是不规则的形状，边缘锐利但具有艺术感，如同时间被打碎后悬浮在空气中。有些碎镜中，映照出她过去与未来不同的样子：有的更年轻纯真，有的成熟冷艳，有的高贵神秘，有的未来感十足，有的带有不同年龄、不同气质、不同命运阶段的她。镜中形象都要保持同一人物的核心辨识度，但在妆容、发型、服饰、气质和时代感上有所区别，形成“同一个人不同人生切片”的感觉。\n\n整个空间梦幻、神秘、唯美，光线以柔和光为主，镜子与碎镜边缘折射出红色、金色、银色与微冷白光，空气中带有轻微雾气、微粒、反射光斑与体积光。整体氛围像梦境、记忆与未来交汇的瞬间，华丽而富有叙事感。画面采用3D CG插画风格，整体明亮，精致、高级、细节丰富",
  },
  {
    id: "dreamy-oriental-emerald-beauty",
    title: "Dreamy Oriental Emerald Beauty",
    englishTitle: "翡翠东方梦境美人",
    source: "imya",
    category: "东方美学",
    image: "/soul-gallery/imya/dreamy-oriental-emerald-beauty.webp",
    width: 675,
    height: 1199,
    description: "翡翠眼眸、蕾丝与金色侧逆光的人像。",
    prompt: "Dreamy oriental female portrait, adult female, close-up portrait, exquisite facial features, fair and translucent skin, delicate but clean skin texture, emerald green eyes, soft and charming gaze, brown slightly curly hair naturally scattered; off-white lace headpiece, cyan-green butterfly embellishments, pearl decorations, clothing is exquisite lace dress, clear structure, clean texture not overly complex, emerald jewelry; lighting is soft warm golden side backlight, clear rim light but not overexposed, skin has slight highlights but not overly reflective, overall light is clean and translucent, background softly blurred, shallow depth of field; high-end portrait photography texture, clear but restrained details, no grain, no noise, real physical lighting, 8K, commercial-grade texture. Aspect ratio: 9:16",
  },
  {
    id: "exotic-dancer-charm",
    title: "Exotic Dancer Charm",
    englishTitle: "异域舞姬魅影",
    source: "imya",
    category: "东方美学",
    image: "/soul-gallery/imya/exotic-dancer-charm.webp",
    width: 675,
    height: 1199,
    description: "沙漠风中，深红轻纱与金色珠宝形成动态。",
    prompt: "一位年轻中国女性，站在沙漠之中，9:16 竖版构图，近景到半身偏全身人像，人物为画面绝对视觉中心。她拥有精致柔美的东方五官，瓷白细腻的肌肤，清透自然的妆容，红润柔软的嘴唇，眼神温柔而迷人，带有淡淡异域神秘感。肩颈线条优雅，锁骨清晰柔美，裸露肩部与上胸区域适度可见，展现自然柔和的性感氛围，她的黑色长发柔顺微卷，在风中自然飘扬，发丝轻盈灵动。\n\n她佩戴华丽精致的异域风金色头饰与额饰，镶嵌红宝石与水晶，耳边垂落长款流苏耳饰，搭配层叠项链、胸前珠宝装饰、腰链与细致金属链条，整体造型奢华而精美。服装为酒红色 的异域舞姬风格长裙，上半身为丝绸光泽感设计，搭配轻透飘逸的薄纱披袖与头纱，衣料在风中大幅度飘动，形成优雅流畅的动态。腰腹线条自然展现，整体氛围性感、迷人，但依然高级克制。\n\n背景为广阔起伏的沙漠 dunes，远处沙丘被夕阳或柔和暖光照亮，天空偏灰蓝色，整体呈现黄昏时分的静谧氛围。风吹动人物发丝与轻纱，营造出电影感与故事感。光影柔和，人物面部清晰细腻，服装与珠宝带有细微闪光颗粒，整体色调以深红、金色、沙金色、暖棕色为主，突出异域风与高贵气质。\n\n风格要求：高质感写实人像，异域公主风，唯美，浪漫，性感，高级精致，电影级光影，真实皮肤质感，超高细节，服装材质精美，珠宝细节丰富，风吹动态强，画面干净，无文字无水印，壁纸级质感。",
  },
  {
    id: "korean-idol-campus-portrait",
    title: "Korean Idol Campus Portrait",
    englishTitle: "韩系偶像校园人像",
    source: "imya",
    category: "时尚人像",
    image: "/soul-gallery/imya/korean-idol-campus-portrait.webp",
    width: 800,
    height: 1200,
    description: "校园石墙与树影里的冷调偶像写真。",
    prompt: "Realistic photography, portrait of a beautiful korean idol with long sleek straight black hair, a slim tall hourglass figure and elegant S-curve body line. She slightly lowers her head and looks at her phone, left arm bent and raised holding the phone, right arm hanging naturally at her side, torso upright yet relaxed, natural poised posture.\n\nShe is wearing a white strapless bodycon mini dress and a black chain crossbody bag. The background is a stone wall with dappled tree shadows cast across it, creating a poetic and textured atmosphere. Fresh campus-inspired fashion editorial mood, youthful and lively yet refined.\n\nExpression: cool, aloof, slightly melancholic, with affectionate and soulful eyes; a lazy, distant gaze toward the camera, subtle emotional tension, cinematic sense of presence.\n\nStyle and mood: dark-toned emotional portrait, immersive atmosphere, hazy aesthetic, retro undertone, slight surrealism, sophisticated and premium visual language, masterpiece composition, cinematic quality, award-winning photography feel, editorial mood portrait.\n\nLighting: soft side lighting with gentle facial fill light, clear facial details, rim light on the hair, strong backlight accents and shadow tracing, dimensional facial features, smooth porcelain skin, soft glow, delicate skin texture, refined retouching, ultra-detailed realism.\n\nComposition: medium close-up to medium shot, shallow depth of field, foreground blur, background blur, rich image layering, strong visual depth, dramatic yet elegant framing, crisp face focus with soft atmospheric surroundings.\n\nVisual qualities: photorealistic, high-end beauty retouching, soft diffusion, subtle bloom, polished skin, clean tonal control, rich texture, high-resolution editorial photography, emotionally charged, cinematic, refined, atmospheric, striking and memorable. --2:3",
  },
  {
    id: "cinematic-street-avant-garde-portrait",
    title: "Cinematic Street Avant-Garde Portrait",
    englishTitle: "电影街头先锋人像",
    source: "imya",
    category: "时尚人像",
    image: "/soul-gallery/imya/cinematic-street-avant-garde-portrait.webp",
    width: 670,
    height: 1200,
    description: "解构针织与暗调街头光线的先锋造型。",
    prompt: "Create a hyper-realistic DSLR cinematic full-body portrait of a stylish young man with sharp, well-defined facial features and a confident, dynamic pose. He is captured in natural yet dramatic lighting with cinematic depth of field, crisp focus, and professional DSLR clarity. He wears an oversized distressed dark brown and beige patchwork knit sweater with contrasting thick stitching, intentional worn holes, and long hanging cords or drawstrings for a raw, avant-garde look, paired with black relaxed-fit cargo pants. He has black over-ear 'gloomyboy' style headphones with a clearly visible wired connection and a minimal metal ring on his hand. Editorial street-fashion aesthetic with ultra-detailed fabric textures, realistic skin tones, subtle film grain, cinematic color grading, shallow depth of field, high contrast, and a moody yet stylish atmosphere.",
  },
  {
    id: "lazy-red-dress-afternoon",
    title: "Lazy Red Dress Afternoon",
    englishTitle: "慵懒红裙午后",
    source: "imya",
    category: "时尚人像",
    image: "/soul-gallery/imya/lazy-red-dress-afternoon.webp",
    width: 900,
    height: 1200,
    description: "午后自然光下的红色缎面生活方式写真。",
    prompt: "Modern apartment living room, late afternoon. Natural window light, soft imperfect daylight with gentle shadows and subtle falloff, warm neutral 4800K, soft ambient indoor lamps in background. Subject: female, balanced natural proportions, realistic anatomy. Pose: reclining on a modern couch, semi-lying position with relaxed posture, one leg slightly bent. Natural candid relaxed expression. Clothing: short spaghetti strap dress, length above mid-thigh, lightweight satin or silk blend with realistic sheen, deep red / crimson red, body-skimming slim fit with natural gravity folds, deep V neckline with subtle chest cleavage, thin spaghetti straps with metallic adjusters. Natural fabric wrinkles from reclining position, soft reflective highlights on satin surface. Skin: natural realistic skin texture, visible pores, minimal smoothing. Hair: loose natural waves spread slightly over couch cushion, shoulder length. Camera: iPhone candid photography, 26mm wide lens, f/1.8, shallow DOF. Premium lifestyle editorial candid, clean neutral tones with warm highlights. Background: neutral beige walls, modern sofa, soft curtains, indoor plants, light oak wooden floor.",
  },
  {
    id: "future-minimal-sportswear",
    title: "Future Minimal Sportswear",
    englishTitle: "未来极简运动装",
    source: "imya",
    category: "商业视觉",
    image: "/soul-gallery/imya/future-minimal-sportswear.webp",
    width: 800,
    height: 1200,
    description: "白色运动装与红粉充气体组成的品牌海报。",
    prompt: "High-fashion futuristic sportswear editorial poster, full-body female model in dynamic wide-leg stance, oversized white minimalist sweatshirt with voluminous sleeves, glossy translucent parachute pants, chunky white-orange athletic sneakers, sleek messy updo hairstyle, gold statement earrings, soft natural makeup, confident editorial expression, studio fashion photography, centered composition, smooth neutral beige gradient background with large abstract glossy red-pink organic 3D inflatable blob shapes behind model, bold oversized white typography “just” partially behind subject, premium athletic brand campaign aesthetic, ultra-clean lighting, soft diffused studio shadows, luxury streetwear advertisement, contemporary magazine cover design, minimalist layout, subtle futuristic graphic microtext, highly polished commercial fashion retouching, sharp focus, cinematic soft contrast, photorealistic, high detail, 8k",
  },
  {
    id: "young-american-woman-fashion-cover",
    title: "Young American Woman Fashion Cover",
    englishTitle: "美式时尚杂志封面",
    source: "imya",
    category: "商业视觉",
    image: "/soul-gallery/imya/young-american-woman-fashion-cover.webp",
    width: 743,
    height: 1200,
    description: "红白配色、玫瑰与汽水构成的杂志封面。",
    prompt: "{\n  \"style\": \"high-end fashion editorial, luxury magazine cover\",\n  \"subject\": {\n    \"type\": \"young American woman\",\n    \"appearance\": {\n      \"hair\": \"long black hair, soft waves\",\n      \"skin\": \"smooth, radiant, natural glow\",\n      \"expression\": \"playful pout, slightly looking aside\",\n      \"makeup\": \"minimal glam, glossy lips, subtle blush\"\n    },\n    \"outfit\": \"red satin off-shoulder crop top with matching high-waist skirt\",\n    \"accessories\": \"small gold hoop earrings, delicate necklace with red heart pendant\"\n  },\n  \"composition\": {\n    \"framing\": \"mid-length portrait, centered\",\n    \"pose\": \"standing, holding objects in both hands\",\n    \"left_hand\": \"glass bottle with red liquid labeled 'Cherry Sparkling Soda'\",\n    \"right_hand\": \"bouquet of fresh red roses wrapped in kraft paper with ribbon\",\n    \"background\": \"clean white studio backdrop\",\n    \"layout\": \"magazine cover layout with strong negative space for typography\"\n  },\n  \"typography\": {\n    \"masthead\": \"ALLURE\",\n    \"masthead_style\": \"large serif font, bold, red color, top center\",\n    \"subtext\": [\n      \"FASHION & LIFESTYLE MAGAZINE\",\n      \"SUMMER 2024 ISSUE\"\n    ],\n    \"cover_lines\": [\n      \"FRESH PERSPECTIVE\",\n      \"GOOD THINGS AHEAD\",\n      \"CONFIDENCE IS YOUR BEST ACCESSORY\",\n      \"SWEET DAYS AHEAD\",\n      \"100% GOOD MOOD\"\n    ],\n    \"style\": \"clean editorial typography, all text in red, modern fashion magazine layout\"\n  },\n  \"lighting\": {\n    \"type\": \"studio lighting\",\n    \"quality\": \"soft diffused light\",\n    \"direction\": \"front-facing with slight side highlights\",\n    \"effect\": \"even skin tones, subtle shadows, glossy fabric highlights\"\n  },\n  \"color_palette\": {\n    \"primary\": [\n      \"red\",\n      \"white\"\n    ],\n    \"accents\": [\n      \"gold\",\n      \"green\"\n    ],\n    \"mood\": \"bold, fresh, confident, romantic\"\n  },\n  \"details\": {\n    \"props\": \"glass bottle with label, realistic roses bouquet\",\n    \"textures\": \"silky fabric, glass reflections, natural skin detail\",\n    \"finish\": \"ultra-realistic, sharp focus, high resolution\"\n  },\n  \"camera\": {\n    \"type\": \"DSLR\",\n    \"lens\": \"85mm portrait lens\",\n    \"aperture\": \"f/2.8\",\n    \"depth_of_field\": \"shallow\",\n    \"focus\": \"sharp on face and product\"\n  },\n  \"aspect_ratio\": \"2:3\",\n  \"quality\": \"8k, ultra-detailed, professional editorial finish\"\n}",
  },
  {
    id: "fashion-model-on-lens",
    title: "Fashion Model On Lens",
    englishTitle: "镜头上的时装模特",
    source: "imya",
    category: "商业视觉",
    image: "/soul-gallery/imya/fashion-model-on-lens.webp",
    width: 1200,
    height: 1200,
    description: "模特与超大长焦镜头融合的科技时尚广告。",
    prompt: "Luxury tech fashion campaign, oversized professional telephoto camera lens placed horizontally like a sculptural object, female model in white shorts and fitted crop top sitting confidently on the lens, one leg bent and one extended downward, sleek ponytail, athletic yet elegant pose, minimal dark studio background, bold oversized typography “FOCUS” behind the model in modern condensed font, glossy reflective floor, cinematic lighting with soft highlights and deep shadows, ultra-clean composition, high-end editorial aesthetic, product integrated naturally with model posture, sharp details, 1:1",
  },
  {
    id: "cinematic-male-travel-poster",
    title: "Cinematic Male Travel Poster",
    englishTitle: "电影感男性旅行海报",
    source: "imya",
    category: "时尚人像",
    image: "/soul-gallery/imya/cinematic-male-travel-poster.webp",
    width: 800,
    height: 1200,
    description: "旅行者侧影与迪拜天际线的双重曝光。",
    prompt: "A cinematic double exposure portrait of a young male traveler in side profile, wearing sunglasses, a casual jacket, and a backpack, holding a map and a camera hanging around his neck. Inside his silhouette, a stunning Dubai cityscape is blended seamlessly  featuring the Burj Khalifa, modern skyscrapers, desert dunes, palm trees, and a coastal shoreline during golden sunset.\nWarm golden light fills the composition, with soft clouds and birds in the sky. The double exposure is clean and well-balanced, with smooth blending between portrait and landscape. Minimal light beige background for a premium poster feel.\nHighly detailed, ultra-realistic textures, cinematic lighting, soft shadows, 85mm lens look, sharp focus, professional travel advertisement style, 8K resolution",
  },
];

export const soulGalleryCategories = ["全部", ...Array.from(new Set(soulGalleryCatalog.map((item) => item.category)))] as const;

export function filterSoulGallery(items: SoulGalleryItem[], query: string, category: string) {
  const normalizedQuery = query.trim().toLocaleLowerCase();
  return items.filter((item) => {
    if (category !== "全部" && item.category !== category) return false;
    if (!normalizedQuery) return true;
    return [item.title, item.englishTitle, item.source, item.category, item.description, item.prompt]
      .some((value) => value.toLocaleLowerCase().includes(normalizedQuery));
  });
}
