import { renderToStaticMarkup } from "react-dom/server";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it } from "vitest";

import { AccountPage } from "@/app/account/page";
import { LoginPage } from "@/app/auth/login/page";
import { RegisterPage } from "@/app/auth/register/page";
import { BillingPage } from "@/app/billing/page";
import { GalleryPage } from "@/app/gallery/page";
import { GenerationProvider } from "@/components/commercial/generation-provider";
import { LanguageProvider } from "@/components/language-provider";

function renderEnglish(element: React.ReactNode) {
  return renderToStaticMarkup(
    <LanguageProvider initialLocale="en-US"><MemoryRouter>{element}</MemoryRouter></LanguageProvider>,
  );
}

describe("commercial account pages", () => {
  it("renders login and registration in English", () => {
    const login = renderEnglish(<LoginPage />);
    const register = renderEnglish(<RegisterPage />);
    expect(login).toContain("Continue creating your next work.");
    expect(login).toContain('placeholder="Email"');
    expect(register).toContain("Sign up and receive starter credits.");
    expect(register).toContain('placeholder="Display name"');
  });

  it("renders account and billing guest states in English", () => {
    const account = renderEnglish(<AccountPage />);
    const billing = renderEnglish(<BillingPage />);
    expect(account).toContain("Log in to view your account");
    expect(billing).toContain("Add and redeem credits");
    expect(billing).toContain("Starter Pack");
  });
  it("renders the works gallery in English", () => {
    const gallery = renderEnglish(<GenerationProvider><GalleryPage /></GenerationProvider>);
    expect(gallery).toContain("My Works");
    expect(gallery).toContain("Only images generated by this account");
    expect(gallery).not.toContain("我的作品");
  });

});
