export type LanguageMode = "zh-CN" | "en-US";
export type TranslationParams = Record<string, string | number>;

type ReadableStorage = Pick<Storage, "getItem">;
type WritableStorage = Pick<Storage, "setItem">;
type LanguageRoot = { lang: string; dataset: Record<string, string> | DOMStringMap };

export const LANGUAGE_STORAGE_KEY = "xinghai-image-studio:language";

export const languageOptions = [
  { value: "zh-CN", label: "中文", shortLabel: "中" },
  { value: "en-US", label: "English", shortLabel: "EN" },
] as const satisfies ReadonlyArray<{ value: LanguageMode; label: string; shortLabel: string }>;

const zhCN = {
  "common.language": "语言",
  "common.appearance": "外观",
  "common.light": "浅色",
  "common.dark": "暗色",
  "common.colorful": "彩色",
  "common.login": "登录",
  "common.register": "注册",
  "common.logout": "退出登录",
  "common.logoutFailed": "退出失败",
  "common.credits": "积分",
  "common.unlimited": "无限配额",
  "common.recharge": "充值",
  "common.contact": "联系邮箱",
  "common.docs": "使用文档",
  "common.items": "{count} 项",
  "common.image": "{count} 张",
  "common.images": "{count} 张",
  "nav.home": "首页",
  "nav.create": "创作",
  "nav.works": "作品",
  "nav.soulGallery": "灵魂画廊",
  "nav.credits": "积分",
  "nav.account": "我的",
  "landing.title": "一站式 AI 图片创作平台。",
  "landing.description": "从灵感到成图，把生成、改图、模板、相册和积分统一在一个简洁工作台里。适合商品主图、头像、海报、漫画分镜和批量素材创作。",
  "landing.start": "开始创作",
  "landing.registerBonus": "注册领取积分",
  "landing.suiteDescription": "提示词模板、参考图、局部编辑、相册和积分消耗清晰可见。",
  "landing.feature.text.title": "文生图",
  "landing.feature.text.body": "输入想法，快速生成商品图、插画、海报和视觉草稿。",
  "landing.feature.image.title": "图生图",
  "landing.feature.image.body": "上传参考图，重绘风格、调整画面和延展创意方向。",
  "landing.feature.edit.title": "局部编辑",
  "landing.feature.edit.body": "保留主体，只修改衣服、背景、道具或局部细节。",
  "landing.feature.gallery.title": "作品相册",
  "landing.feature.gallery.body": "自动保存最近作品，方便回看、下载和继续创作。",
  "studio.title": "图像创作",
  "studio.defaultPrompt": "流星雨划过澄澈夜空，远处山脊与湖面倒影，真实摄影，广角构图",
  "studio.template.photo": "真实摄影",
  "studio.template.product": "商业主图",
  "studio.template.anime": "动漫角色",
  "studio.template.storyboard": "漫画分镜",
  "studio.template.render3d": "3D 渲染",
  "studio.template.background": "换背景",
  "studio.template.character": "统一角色",
  "studio.template.gray": "高级灰调色",
  "studio.estimatedCredits": "预计 {count} 积分",
  "studio.creationType": "创作类型",
  "studio.chooseFeature": "选择要使用的功能",
  "studio.spectrum": "灵感光谱",
  "studio.interfaceColor": "界面色彩",
  "studio.spectrumHelp": "选择浅色、暗色或彩色界面。",
  "studio.loginNotice": "登录后可生成图片、保存作品和管理积分。",
  "studio.goLogin": "去登录",
  "studio.uploadAssets": "上传素材",
  "studio.uploadImage": "上传图片",
  "studio.mask": "遮罩",
  "studio.sourceImage": "源图",
  "studio.removeAsset": "移除素材",
  "studio.model": "模型",
  "studio.chooseModel": "选择要使用的型号",
  "studio.currentModel": "当前生成模型",
  "studio.ratio": "比例",
  "studio.chooseRatio": "选择宽高比",
  "studio.canvasSync": "画布同步变化",
  "studio.imageRatio": "图片比例 {ratio}",
  "studio.count": "生成张数",
  "studio.countRange": "1–4 张",
  "studio.resolution": "分辨率",
  "studio.outputClarity": "输出清晰度",
  "studio.standard": "标准",
  "studio.hd": "高清",
  "studio.ultra": "超清",
  "studio.templates": "提示词模板",
  "studio.templateHelp": "点击名称填入提示词框",
  "studio.collapse": "收起",
  "studio.more": "更多 →",
  "studio.prompt": "提示词",
  "studio.promptHelp": "输入提示词即可生成图片。",
  "studio.promptLabel": "图片生成提示词",
  "studio.cost": "预计消耗 {count} 积分",
  "studio.generating": "生成中",
  "studio.generate": "生成",
  "studio.result": "{count} 张结果",
  "studio.resultCount": "{count} 张结果",
  "studio.mode.text.label": "文生图",
  "studio.mode.text.short": "文生图",
  "studio.mode.text.description": "输入提示词生成图片",
  "studio.mode.image.label": "图生图",
  "studio.mode.image.short": "图生图",
  "studio.mode.image.description": "上传参考图后重绘",
  "studio.mode.edit.label": "局部编辑",
  "studio.mode.edit.short": "局部编辑",
  "studio.mode.edit.description": "上传遮罩做局部修改",
  "studio.mode.remove-bg.label": "去背景",
  "studio.mode.remove-bg.short": "去背景",
  "studio.mode.remove-bg.description": "快速抠出主体",
  "studio.mode.upscale.label": "图片放大",
  "studio.mode.upscale.short": "放大",
  "studio.mode.upscale.description": "提升清晰度和细节",
  "studio.mode.background.label": "换背景",
  "studio.mode.background.short": "换背景",
  "studio.mode.background.description": "保留主体替换场景",
  "studio.mode.batch.label": "批量一致性",
  "studio.mode.batch.short": "批量",
  "studio.mode.batch.description": "角色和分镜批量生成",
  "studio.error.login": "请先登录后再创作",
  "studio.error.prompt": "请输入提示词后再生成图片",
  "studio.error.upload": "这个功能需要先上传图片",
  "studio.error.mask": "局部编辑需要上传遮罩图",
  "studio.error.readImage": "图片读取失败",
  "studio.error.create": "创建图片任务失败",
  "studio.submitted": "任务已提交，切换页面不会中断生成",
  "preview.title": "生成预览",
  "preview.description": "完整显示、不裁切；生成后可缩放并打开原图",
  "preview.status.generating": "生成中",
  "preview.status.failed": "生成失败",
  "preview.status.idle": "空闲",
  "preview.zoomOut": "缩小预览",
  "preview.zoomIn": "放大预览",
  "preview.fit": "适应画布",
  "preview.openOriginal": "打开原图",
  "preview.generatingImage": "正在生成图片",
  "preview.waited": "第 {index} 张 · 已等待 {time}",
  "preview.retryNote": "参数已保留，可直接重新生成。",
  "preview.resultAlt": "生成结果 {index}",
  "preview.waiting": "等待生成",
  "preview.waitingHelp": "左侧填写提示词和参数，点击生成后会立即显示任务状态。",
  "preview.info": "本次生成信息",
  "preview.engine": "当前引擎",
  "preview.available": "服务可用",
  "preview.output": "输出参数",
  "preview.quantity": "数量",
  "preview.sync": "作品同步",
  "preview.palette": "灵感色板",
  "preview.sync.generatingTitle": "正在生成",
  "preview.sync.errorTitle": "本次未保存",
  "preview.sync.savedTitle": "已保存作品",
  "preview.sync.waitTitle": "等待开始",
  "preview.sync.generatingNote": "任务已提交，完成后自动同步",
  "preview.sync.errorNote": "参数已保留，可重新提交",
  "preview.sync.savedNote": "{count} 张结果已进入作品",
  "preview.sync.waitNote": "生成完成后自动保存到作品",
  "preview.footer.processing": "生成任务处理中",
  "preview.footer.failed": "任务失败",
  "preview.footer.complete": "生成完成 · {count} 张",
  "preview.footer.ready": "准备就绪",
  "preview.footer.zoomHelp": "Ctrl/⌘ + 滚轮缩放 · 放大后拖拽查看",
  "preview.footer.openHelp": "点击结果打开原图",
  "gallery.kicker": "作品管理",
  "gallery.title": "我的作品",
  "gallery.description": "这里只显示当前账号生成的作品，任务完成后会自动更新。",
  "gallery.refresh": "刷新作品",
  "gallery.clear": "清空",
  "gallery.generating": "图片生成中，完成后会自动加入作品",
  "gallery.syncing": "正在同步当前账号作品",
  "gallery.loginHelp": "登录后可以查看和管理作品。",
  "gallery.empty": "当前账号暂无作品，先去创作页生成图片。",
  "gallery.loadFailed": "作品加载失败",
  "gallery.cleared": "作品已清空",
  "gallery.clearFailed": "清空失败",
  "soul.title": "灵魂画廊",
  "soul.description": "来自 imagic6 与 imya 的精选视觉模板。看成图、读提示词，再把灵感一键带进创作台。",
  "soul.stat.all": "19 组精选灵感",
  "soul.stat.future": "8 组未来场景",
  "soul.stat.fashion": "11 组时尚模板",
  "soul.searchLabel": "搜索灵魂画廊",
  "soul.searchPlaceholder": "搜索标题、风格或提示词",
  "soul.showing": "当前显示 {count} 项",
  "soul.local": "本地素材，打开更快",
  "soul.sectionTitle": "找到下一张值得生成的图",
  "soul.sectionHelp": "点击图片查看完整提示词",
  "soul.categories": "灵魂画廊分类",
  "soul.viewPrompt": "查看 {title} 提示词",
  "soul.empty": "没有匹配的灵感",
  "soul.clearFilter": "清除筛选",
  "soul.fullPrompt": "完整提示词",
  "soul.characters": "{count} 字符",
  "soul.copied": "已复制",
  "soul.copy": "复制提示词",
  "soul.bring": "带入创作",
  "soul.copySuccess": "提示词已复制",
  "soul.copyFailed": "复制失败，请在详情中手动选择提示词",
  "billing.kicker": "积分中心",
  "billing.title": "充值和兑换",
  "billing.balanceUnlimited": "当前账号为管理员无限配额。",
  "billing.balance": "当前余额：{count} 积分。",
  "billing.loginHelp": "登录后可查看余额、使用兑换码和购买积分包。",
  "billing.codePlaceholder": "输入兑换码",
  "billing.redeem": "兑换",
  "billing.noCharge": "无需充值，生成不扣积分",
  "billing.loginFirst": "先登录",
  "billing.enterCode": "请输入兑换码",
  "billing.success": "兑换成功，积分已到账",
  "billing.failed": "兑换失败",
  "billing.plan.light.name": "轻量包",
  "billing.plan.light.desc": "适合少量试用和头像创作",
  "billing.plan.creator.name": "创作者包",
  "billing.plan.creator.desc": "适合日常商品图和海报创作",
  "billing.plan.studio.name": "工作室包",
  "billing.plan.studio.desc": "适合批量素材和团队创作",
  "account.loginTitle": "登录后查看账户",
  "account.loginHelp": "账户、积分和作品记录会统一保存在你的个人空间里。",
  "account.title": "我的账户",
  "account.description": "管理账户资料、积分余额和创作记录。",
  "account.username": "用户名：{value}",
  "account.email": "邮箱：{value}",
  "account.admin": "管理员账号",
  "auth.login.hero": "继续创作你的下一张作品。",
  "auth.login.heroHelp": "登录后可使用积分、查看作品相册，并继续上次的创作流程。",
  "auth.login.help": "使用邮箱和密码进入你的创作空间。",
  "auth.email": "邮箱",
  "auth.password": "密码",
  "auth.login.success": "登录成功",
  "auth.login.failed": "登录失败",
  "auth.login.noAccount": "还没有账号？",
  "auth.login.registerNow": "立即注册",
  "auth.register.hero": "注册即可领取初始积分。",
  "auth.register.heroHelp": "使用兑换码可获得更多积分，适合快速体验文生图、图生图和局部编辑。",
  "auth.register.help": "创建账号后即可开始创作。",
  "auth.register.loadingPolicy": "正在读取注册规则…",
  "auth.register.policyFailed": "注册规则加载失败",
  "auth.register.reload": "重新加载",
  "auth.register.closed": "当前暂未开放注册，请稍后再试。",
  "auth.register.allowed": "允许注册的邮箱：{domains}",
  "auth.name": "昵称",
  "auth.emailAllowed": "邮箱，仅支持 {domains}",
  "auth.passwordMin": "密码，至少 6 位",
  "auth.phone": "手机号",
  "auth.sms": "短信验证码",
  "auth.redeemOptional": "兑换码，可选",
  "auth.register.loading": "正在加载注册规则",
  "auth.register.creating": "正在创建账号",
  "auth.register.create": "创建账号",
  "auth.register.success": "注册成功，积分已发放",
  "auth.register.failed": "注册失败",
  "auth.register.policyNotReady": "注册规则尚未加载完成",
  "auth.register.closedShort": "当前暂未开放注册",
  "auth.register.emailOnly": "邮箱仅支持 {domains}",
  "auth.register.enterPhone": "请输入手机号",
  "auth.register.enterSms": "请输入短信验证码",
  "auth.register.haveAccount": "已有账号？",
  "auth.register.goLogin": "去登录",
} as const;

type TranslationKey = keyof typeof zhCN;

const enUS: Record<TranslationKey, string> = {
  "common.language": "Language",
  "common.appearance": "Appearance",
  "common.light": "Light",
  "common.dark": "Dark",
  "common.colorful": "Colorful",
  "common.login": "Log in",
  "common.register": "Sign up",
  "common.logout": "Log out",
  "common.logoutFailed": "Log out failed",
  "common.credits": "credits",
  "common.unlimited": "Unlimited",
  "common.recharge": "Add credits",
  "common.contact": "Contact",
  "common.docs": "Documentation",
  "common.items": "{count} items",
  "common.image": "{count} image",
  "common.images": "{count} images",
  "nav.home": "Home",
  "nav.create": "Create",
  "nav.works": "Works",
  "nav.soulGallery": "Soul Gallery",
  "nav.credits": "Credits",
  "nav.account": "Account",
  "landing.title": "One workspace for AI image creation.",
  "landing.description": "Move from inspiration to finished images with generation, editing, templates, galleries, and credits in one focused workspace. Built for product shots, avatars, posters, storyboards, and batch assets.",
  "landing.start": "Start creating",
  "landing.registerBonus": "Sign up for credits",
  "landing.suiteDescription": "Prompt templates, references, local edits, galleries, and credit usage stay clear at every step.",
  "landing.feature.text.title": "Text to image",
  "landing.feature.text.body": "Turn an idea into product imagery, illustrations, posters, and visual drafts.",
  "landing.feature.image.title": "Image to image",
  "landing.feature.image.body": "Upload a reference to restyle, refine, and explore new visual directions.",
  "landing.feature.edit.title": "Local editing",
  "landing.feature.edit.body": "Keep the subject while changing clothing, backgrounds, props, or details.",
  "landing.feature.gallery.title": "Work gallery",
  "landing.feature.gallery.body": "Save recent work automatically for review, download, and continued creation.",
  "studio.title": "Image Studio",
  "studio.defaultPrompt": "A meteor shower crossing a clear night sky, distant mountain ridge reflected in a lake, realistic photography, wide-angle composition",
  "studio.template.photo": "Realistic photo",
  "studio.template.product": "Product hero",
  "studio.template.anime": "Anime character",
  "studio.template.storyboard": "Storyboard",
  "studio.template.render3d": "3D render",
  "studio.template.background": "New background",
  "studio.template.character": "Character consistency",
  "studio.template.gray": "Cinematic gray",
  "studio.estimatedCredits": "Est. {count} credits",
  "studio.creationType": "Creation type",
  "studio.chooseFeature": "Choose a workflow",
  "studio.spectrum": "Inspiration spectrum",
  "studio.interfaceColor": "Interface color",
  "studio.spectrumHelp": "Choose a light, dark, or colorful interface.",
  "studio.loginNotice": "Log in to generate images, save works, and manage credits.",
  "studio.goLogin": "Log in",
  "studio.uploadAssets": "Upload assets",
  "studio.uploadImage": "Upload image",
  "studio.mask": "Mask",
  "studio.sourceImage": "Source",
  "studio.removeAsset": "Remove asset",
  "studio.model": "Model",
  "studio.chooseModel": "Choose a generation model",
  "studio.currentModel": "Current model",
  "studio.ratio": "Aspect ratio",
  "studio.chooseRatio": "Choose a canvas ratio",
  "studio.canvasSync": "Canvas updates live",
  "studio.imageRatio": "Image ratio {ratio}",
  "studio.count": "Image count",
  "studio.countRange": "1–4 images",
  "studio.resolution": "Resolution",
  "studio.outputClarity": "Output detail",
  "studio.standard": "Standard",
  "studio.hd": "High",
  "studio.ultra": "Ultra",
  "studio.templates": "Prompt templates",
  "studio.templateHelp": "Click a name to fill the prompt",
  "studio.collapse": "Collapse",
  "studio.more": "More →",
  "studio.prompt": "Prompt",
  "studio.promptHelp": "Describe the image you want to generate.",
  "studio.promptLabel": "Image generation prompt",
  "studio.cost": "Estimated cost: {count} credits",
  "studio.generating": "Generating",
  "studio.generate": "Generate",
  "studio.result": "{count} result",
  "studio.resultCount": "{count} results",
  "studio.mode.text.label": "Text to image",
  "studio.mode.text.short": "Text to image",
  "studio.mode.text.description": "Generate from a prompt",
  "studio.mode.image.label": "Image to image",
  "studio.mode.image.short": "Image to image",
  "studio.mode.image.description": "Redraw from a reference",
  "studio.mode.edit.label": "Local edit",
  "studio.mode.edit.short": "Local edit",
  "studio.mode.edit.description": "Edit with an uploaded mask",
  "studio.mode.remove-bg.label": "Remove background",
  "studio.mode.remove-bg.short": "Remove BG",
  "studio.mode.remove-bg.description": "Extract the subject quickly",
  "studio.mode.upscale.label": "Upscale",
  "studio.mode.upscale.short": "Upscale",
  "studio.mode.upscale.description": "Increase clarity and detail",
  "studio.mode.background.label": "Replace background",
  "studio.mode.background.short": "Background",
  "studio.mode.background.description": "Keep the subject, change the scene",
  "studio.mode.batch.label": "Batch consistency",
  "studio.mode.batch.short": "Batch",
  "studio.mode.batch.description": "Create consistent characters and shots",
  "studio.error.login": "Log in before creating",
  "studio.error.prompt": "Enter a prompt before generating",
  "studio.error.upload": "This workflow requires an uploaded image",
  "studio.error.mask": "Local editing requires a mask image",
  "studio.error.readImage": "Could not read the image",
  "studio.error.create": "Could not create the image task",
  "studio.submitted": "Task submitted. Generation continues when you change pages.",
  "preview.title": "Generation preview",
  "preview.description": "See the full image without cropping, then zoom or open the original.",
  "preview.status.generating": "Generating",
  "preview.status.failed": "Failed",
  "preview.status.idle": "Idle",
  "preview.zoomOut": "Zoom out",
  "preview.zoomIn": "Zoom in",
  "preview.fit": "Fit to canvas",
  "preview.openOriginal": "Open original",
  "preview.generatingImage": "Generating image",
  "preview.waited": "Image {index} · {time} elapsed",
  "preview.retryNote": "Your settings are preserved. Submit again when ready.",
  "preview.resultAlt": "Generated result {index}",
  "preview.waiting": "Ready to create",
  "preview.waitingHelp": "Set your prompt and parameters on the left, then generate to see live task status.",
  "preview.info": "Generation details",
  "preview.engine": "Current engine",
  "preview.available": "Service available",
  "preview.output": "Output settings",
  "preview.quantity": "Quantity",
  "preview.sync": "Work sync",
  "preview.palette": "Inspiration palette",
  "preview.sync.generatingTitle": "Generating",
  "preview.sync.errorTitle": "Not saved",
  "preview.sync.savedTitle": "Saved to works",
  "preview.sync.waitTitle": "Waiting to start",
  "preview.sync.generatingNote": "Submitted and syncing automatically when complete",
  "preview.sync.errorNote": "Settings are preserved for another submission",
  "preview.sync.savedNote": "Added to Works: {count}",
  "preview.sync.waitNote": "Completed images are saved to Works automatically",
  "preview.footer.processing": "Generation in progress",
  "preview.footer.failed": "Task failed",
  "preview.footer.complete": "Complete · {count}",
  "preview.footer.ready": "Ready",
  "preview.footer.zoomHelp": "Ctrl/⌘ + wheel to zoom · drag when enlarged",
  "preview.footer.openHelp": "Click a result to open the original",
  "gallery.kicker": "WORK MANAGEMENT",
  "gallery.title": "My Works",
  "gallery.description": "Only images generated by this account appear here. The gallery updates when a task completes.",
  "gallery.refresh": "Refresh",
  "gallery.clear": "Clear",
  "gallery.generating": "An image is being generated and will appear here automatically.",
  "gallery.syncing": "Syncing works for this account",
  "gallery.loginHelp": "Log in to view and manage your works.",
  "gallery.empty": "No works yet. Create your first image in the studio.",
  "gallery.loadFailed": "Could not load works",
  "gallery.cleared": "Works cleared",
  "gallery.clearFailed": "Could not clear works",
  "soul.title": "Soul Gallery",
  "soul.description": "A curated visual library from imagic6 and imya. Explore finished images, read the prompts, and carry inspiration into the studio.",
  "soul.stat.all": "19 curated ideas",
  "soul.stat.future": "8 future scenes",
  "soul.stat.fashion": "11 fashion templates",
  "soul.searchLabel": "Search Soul Gallery",
  "soul.searchPlaceholder": "Search titles, styles, or prompts",
  "soul.showing": "Showing {count} items",
  "soul.local": "Local assets for faster viewing",
  "soul.sectionTitle": "Find the next image worth creating",
  "soul.sectionHelp": "Click an image to view its full prompt",
  "soul.categories": "Soul Gallery categories",
  "soul.viewPrompt": "View the prompt for {title}",
  "soul.empty": "No matching inspiration",
  "soul.clearFilter": "Clear filters",
  "soul.fullPrompt": "Full prompt",
  "soul.characters": "{count} characters",
  "soul.copied": "Copied",
  "soul.copy": "Copy prompt",
  "soul.bring": "Use in Studio",
  "soul.copySuccess": "Prompt copied",
  "soul.copyFailed": "Copy failed. Select the prompt manually in the detail view.",
  "billing.kicker": "CREDIT CENTER",
  "billing.title": "Add and redeem credits",
  "billing.balanceUnlimited": "This administrator account has unlimited credits.",
  "billing.balance": "Current balance: {count} credits.",
  "billing.loginHelp": "Log in to see your balance, redeem codes, and choose a credit pack.",
  "billing.codePlaceholder": "Enter redemption code",
  "billing.redeem": "Redeem",
  "billing.noCharge": "No top-up needed. Generation does not deduct credits.",
  "billing.loginFirst": "Log in first",
  "billing.enterCode": "Enter a redemption code",
  "billing.success": "Redeemed successfully. Credits added.",
  "billing.failed": "Redemption failed",
  "billing.plan.light.name": "Starter Pack",
  "billing.plan.light.desc": "For light trials and avatar creation",
  "billing.plan.creator.name": "Creator Pack",
  "billing.plan.creator.desc": "For everyday product imagery and posters",
  "billing.plan.studio.name": "Studio Pack",
  "billing.plan.studio.desc": "For batch assets and team workflows",
  "account.loginTitle": "Log in to view your account",
  "account.loginHelp": "Your account, credits, and works stay together in your personal space.",
  "account.title": "My Account",
  "account.description": "Manage profile details, credit balance, and creation history.",
  "account.username": "Username: {value}",
  "account.email": "Email: {value}",
  "account.admin": "Administrator",
  "auth.login.hero": "Continue creating your next work.",
  "auth.login.heroHelp": "Log in to use credits, view your gallery, and continue your latest workflow.",
  "auth.login.help": "Use your email and password to enter your creative space.",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.login.success": "Logged in",
  "auth.login.failed": "Login failed",
  "auth.login.noAccount": "New here?",
  "auth.login.registerNow": "Create an account",
  "auth.register.hero": "Sign up and receive starter credits.",
  "auth.register.heroHelp": "Use redemption codes for more credits and quickly try text-to-image, image-to-image, and local editing.",
  "auth.register.help": "Create an account to start making images.",
  "auth.register.loadingPolicy": "Loading registration rules…",
  "auth.register.policyFailed": "Could not load registration rules",
  "auth.register.reload": "Reload",
  "auth.register.closed": "Registration is closed for now. Please try again later.",
  "auth.register.allowed": "Allowed email domains: {domains}",
  "auth.name": "Display name",
  "auth.emailAllowed": "Email — supported domains: {domains}",
  "auth.passwordMin": "Password — at least 6 characters",
  "auth.phone": "Phone number",
  "auth.sms": "SMS verification code",
  "auth.redeemOptional": "Redemption code (optional)",
  "auth.register.loading": "Loading registration rules",
  "auth.register.creating": "Creating account",
  "auth.register.create": "Create account",
  "auth.register.success": "Account created and starter credits added",
  "auth.register.failed": "Registration failed",
  "auth.register.policyNotReady": "Registration rules are not ready yet",
  "auth.register.closedShort": "Registration is currently closed",
  "auth.register.emailOnly": "Email must use {domains}",
  "auth.register.enterPhone": "Enter your phone number",
  "auth.register.enterSms": "Enter the SMS verification code",
  "auth.register.haveAccount": "Already have an account?",
  "auth.register.goLogin": "Log in",
};

export function normalizeLanguageMode(value: string | null | undefined): LanguageMode {
  if (value === "en" || value === "en-US") return "en-US";
  return "zh-CN";
}

export function readStoredLanguageMode(storage?: ReadableStorage | null): LanguageMode {
  const target = storage ?? (typeof window === "undefined" ? null : window.localStorage);
  if (!target) return "zh-CN";
  try {
    return normalizeLanguageMode(target.getItem(LANGUAGE_STORAGE_KEY));
  } catch {
    return "zh-CN";
  }
}

export function persistLanguageMode(locale: LanguageMode, storage?: WritableStorage | null) {
  const target = storage ?? (typeof window === "undefined" ? null : window.localStorage);
  if (!target) return;
  try {
    target.setItem(LANGUAGE_STORAGE_KEY, locale);
  } catch {
    // 本地存储不可用时，当前页面内仍可正常切换。
  }
}

export function applyLanguageMode(locale: LanguageMode, root?: LanguageRoot | null) {
  const target = root ?? (typeof document === "undefined" ? null : document.documentElement);
  if (!target) return;
  target.lang = locale;
  target.dataset.language = locale;
}

export function createTranslator(locale: LanguageMode) {
  const dictionary = locale === "en-US" ? enUS : zhCN;
  return (key: TranslationKey, params?: TranslationParams) => {
    let value: string = dictionary[key];
    if (!params) return value;
    Object.entries(params).forEach(([name, replacement]) => {
      value = value.replaceAll(`{${name}}`, String(replacement));
    });
    return value;
  };
}

export type Translate = ReturnType<typeof createTranslator>;
export type { TranslationKey };
